Repository 1poon2poon/front, pull requests merged in 2025-02, with the labels that each got.

#16 [주환] Btn, PressMotion 컴포넌트 제작
  package-lock.json
  package.json
  src/components/Btn.tsx
  src/components/PressMotion.tsx
  src/pages/donate/DonateMain.tsx
  src/pages/invest/InvestMain.tsx
  src/pages/main/Main.tsx
Labels: component

#9 Feat: TitleBox 컴포넌트 생성
  src/components/NonTitleBox.tsx
  src/components/TitleBox.tsx
Labels: component

#21 [주환] Guage 컴포넌트 제작
  src/components/Guage.tsx
  src/components/ex.tsx
Labels: component

#23 [형선] PointBox 컴포넌트 추가
  src/assets/PointBox/PointImg.png
  src/assets/StampBox/BusIcon.png
  src/assets/StampBox/CafeIcon.png
  src/assets/StampBox/FoodIcon.png
  src/assets/StampBox/MovieIcon.png
  src/assets/StampBox/StoreIcon.png
  src/assets/StampBox/TaxiIcon.png
  src/assets/ex.tsx
  src/components/PointBox.tsx
  src/components/StampBox.tsx
Labels: component

#25 [혜미] CategoryBox 생성
  src/assets/categorybox/books_image.png
  src/assets/categorybox/building_image.png
  src/assets/categorybox/computer_image.png
  src/assets/categorybox/dog_image.png
  src/assets/categorybox/dove_image.png
  src/assets/categorybox/earth_image.png
  src/assets/categorybox/home_img.png
  src/assets/categorybox/hospital_image.png
  src/assets/categorybox/money_image.png
  src/assets/categorybox/shopping_image.png
  src/components/CategoryBox.tsx
  src/pages/main/Main.tsx
Labels: component

#29 [형선] ETFBox 컴포넌트 추가, PointBox 숫자 포매팅 수정
  src/assets/ETFBox/ETFIcon.png
  src/components/ETFBox.tsx
  src/components/PointBox.tsx
Labels: fix, component

#30 [혜미] 메인페이지 캐시백 영역 디자인 구현
  src/assets/CashbackIcon.png
  src/assets/Vector.png
  src/components/CategoryBox.tsx
  src/components/StampBox.tsx
  src/pages/main/Main.tsx
Labels: page

#34 [혜미] 캐시백 서비스 제작
  src/assets/donateIcon.png
  src/assets/investDownIcon.png
  src/assets/investUpIcon.png
  src/pages/main/Main.tsx
Labels: page

#36 [혜미] 캐시백 스탬프판 제작
  src/assets/Coin/100coin.png
  src/assets/Coin/500coin.png
  src/pages/main/Main.tsx
Labels: page
