Repository 1poon2poon/front, pull requests merged in 2025-03, with the labels that each got.

#40 [형선] 기부 설정 전 페이지 추가
  src/App.tsx
  src/assets/InvestPage/Invest.json
  src/assets/characterbox/present.json
  src/assets/donatePage/Donation.json
  src/assets/donatePage/Donation.png
  src/components/CategoryBox.tsx
  src/components/CharacterBox.tsx
  src/components/PointBox.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMain.tsx
  src/pages/donate/DonateMainBefore.tsx
  src/pages/invest/InvestMainBefore.tsx
  src/pages/main/Main.tsx
Labels: page

#38 [혜미] 스탬프판 동전 애니메이션 구현
  src/App.tsx
  src/components/CoinRotate.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: component

#48 [혜미] 포인트 상세페이지 제작
  src/App.tsx
  src/assets/DownArrow.png
  src/assets/UsageIcon.png
  src/assets/check_blue.png
  src/assets/check_grey.png
  src/pages/main/PointHistory.tsx
Labels: page

#50 (채연) 투자 카테고리, ETF상세 페이지 끝/ ETF추천, ETF 카테고리별 리스트 개발 중
  package-lock.json
  package.json
  src/App.tsx
  src/components/CandlestickChart.tsx
  src/components/CandlestickTopGainersChart.tsx
  src/components/CategoryBox.tsx
  src/components/ETFBox.tsx
  src/components/TopGainersChart.tsx
  src/data/etfData.ts
  src/pages/invest/Category.tsx
  src/pages/invest/ETFCategoryList.tsx
  src/pages/invest/ETFDetail.tsx
  src/pages/invest/ETFList.tsx
  src/server/server.ts
  tsconfig.json
Labels: page, component

#55 [주환] 뒤로가기 기능, y축 스크롤 기능 추가
  src/App.tsx
  src/layout/DefaultLayout.tsx
  src/layout/PlusLayout.tsx
  src/styles/GlobalStyles.tsx
Labels: component

#58 [형선] 기부 페이지들 다음 버튼 수정, 목표 금액 input css 수정
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMainBefore.tsx
  src/pages/invest/InvestMainBefore.tsx
Labels: fix

#59 Feat: 캐시백 영역, 스탬프판, 포인트 합산 기능 구현
  src/assets/Main/CashbackIcon.png
  src/assets/Main/DownArrow.png
  src/assets/Main/UsageIcon.png
  src/assets/Main/Vector.png
  src/assets/Main/check_blue.png
  src/assets/Main/check_grey.png
  src/assets/Main/donateIcon.png
  src/assets/Main/investDownIcon.png
  src/assets/Main/investUpIcon.png
  src/components/StampBox.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: page

#64 [혜미] 메인 페이지 컴포넌트 분리 및 코드 정리
  package-lock.json
  package.json
  src/assets/banner1.png
  src/assets/banner2.png
  src/components/Main/AdBanner.tsx
  src/components/Main/CashbackSection.tsx
  src/components/Main/CashbackServiceSection.tsx
  src/components/Main/PointHistorySection.tsx
  src/components/Main/StampBoardSection.tsx
  src/pages/main/Main.tsx
Labels: refactor

#66 [형선] 기부 메인 페이지 기능 추가
  src/App.tsx
  src/components/CharacterBox.tsx
  src/components/Main/CashbackServiceSection.tsx
  src/components/Main/PointHistorySection.tsx
  src/components/Main/StampBoardSection.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMainBefore.tsx
  src/pages/main/Main.tsx
Labels: fix, page, component

#67 [혜미] 컴포넌트 경로 수정
  src/components/Main/PointHistorySection.tsx
  src/components/Main/StampBoardSection.tsx
Labels: fix

#71 [혜미] 적립/사용 내역 색상 구분, 필터 기능 구현
  src/components/Main/AdBanner.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: page

#73 [혜미] 포인트 상세내역 최신순으로 정렬
  src/pages/main/PointHistory.tsx
Labels: page

#75 [채연] ETFList.tsx 수정
  src/pages/invest/ETFList.tsx
  src/pages/invest/InvestmentHome.tsx
Labels: fix

#77 [혜미] 광고 배너 슬라이드 이미지 사이 간격 추가
  src/components/Main/AdBanner.tsx
Labels: page

#84 [혜미] Etf 이미지 크기 작게 수정
  src/components/ETFBox.tsx
  src/components/Main/StampBoardSection.tsx
  src/pages/main/Main.tsx
Labels: component

#86 [형선] 기부 메인 기능 추가
  src/App.tsx
  src/assets/donatePage/BooksBadge.png
  src/assets/donatePage/BooksPage.png
  src/assets/donatePage/DogBadge.png
  src/assets/donatePage/DogPage.png
  src/assets/donatePage/DoveBadge.png
  src/assets/donatePage/DovePage.png
  src/assets/donatePage/EarthBadge.png
  src/assets/donatePage/EarthPage.png
  src/assets/donatePage/HomeBadge.png
  src/assets/donatePage/HomePage.png
  src/assets/donatePage/HosBadge.png
  src/assets/donatePage/HosPage.png
  src/assets/donatePage/PoonStamp.png
  src/components/CharacterBox.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
Labels: fix, page

#90 [채연] ETFList.tsx (즐겨 찾기 기능 삭제), ETFBox.tsx(즐겨 찾기 기능 삭제), ETFDetail.tsx (즐겨 찾기 기능 추가), HomeLayout.tsx (홈 버튼)
  src/App.tsx
  src/components/ETFBox.tsx
  src/components/ETFQuantityBox.tsx
  src/layout/HomeLayout.tsx
  src/pages/invest/ETFDetail.tsx
  src/pages/invest/ETFList.tsx
Labels: fix, page

#88 [혜미] 광고 배너 높이 수정
  src/components/Main/AdBanner.tsx
Labels: component

#100 [주환] 기부 목표 설정 완료 페이지 제작
  package-lock.json
  package.json
  src/App.tsx
  src/assets/donatePage/Heart.json
  src/components/Btn.tsx
  src/components/PressMotion.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateSetFinish.tsx
Labels: page

#101 [혜미] 동전 회전 효과 수정
  src/assets/Coin/100coinback.png
  src/assets/Coin/500coinback.png
  src/components/FlipImage.tsx
  src/components/Main/StampBoardSection.tsx
Labels: component

#102 [형선] 기부 메인 페이지 수정
  src/App.tsx
  src/assets/characterbox/getCoin.json
  src/components/Donate/CharacterBox.tsx
  src/components/Donate/DonateNonTitleBox.tsx
  src/components/Donate/Guage.tsx
  src/layout/DonateMainLayout.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMainBefore.tsx
Labels: fix, page, component

#105 [주환] axios 인스턴스 설정(baseAxios), 전역 상태 관리 설정(zustand) 및 main 페이지에서 초기 유저 데이터 설정
  .gitignore
  package-lock.json
  package.json
  src/apis/axiosInstance.tsx
  src/apis/ex.tsx
  src/pages/main/Main.tsx
  src/store/User.tsx
  src/types/env.d.ts
Labels: component, api

#110 [혜미] 전역 상태 stamp 관리 수정
  src/pages/main/Main.tsx
  src/store/User.tsx
Labels: component

#113 [혜미] 동전 배경 제거, 메인 페이지 전역 변수 설정, 포인트 내역 클릭시 pressmotion 효과 추가, 메인&포인트 내역 페이지 간 포인트 연결
  src/components/FlipImage.tsx
  src/components/Main/CashbackSection.tsx
  src/components/Main/PointHistorySection.tsx
  src/components/Main/StampBoardSection.tsx
  src/components/NonTitleBox.tsx
  src/components/PointBox.tsx
  src/components/PressMotion.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
  src/store/User.tsx
Labels: page

#118 [주환] 포인트 내역 페이지 css 수정, GlobalStyles padding 삭제
  src/components/Main/AdBanner.tsx
  src/components/Main/PointHistorySection.tsx
  src/components/TitleBox.tsx
  src/layout/DefaultLayout.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
  src/styles/GlobalStyles.tsx
Labels: page

#119 [혜미] 상황별 기부 연결 링크 추가, PointBox Css 수정, 기부 진행률 추가, PointHistory 필터 Pressmot ion 기능 추가
  src/components/Main/CashbackServiceSection.tsx
  src/components/PointBox.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: page

#121 [혜미] Feat: filter overlay 클릭시 필터 탭 닫히는 기능 구현, main.tsx&pointhistory.tsx 좌우 padding 여백 추가
  src/components/Main/CashbackServiceSection.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
  src/store/User.tsx
Labels: page

#123 [혜미] 상황별 투자 연결 링크 추가
  src/components/Main/CashbackServiceSection.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
  src/store/User.tsx
Labels: page

#126 [혜미] 포인트 전환 버튼 클릭시 배열 초기화
  src/components/Main/AdBanner.tsx
  src/components/Main/FlipImage.tsx
  src/components/Main/StampBoardAnimation.tsx
  src/components/Main/StampBoardSection.tsx
  src/pages/main/Main.tsx
Labels: page

#129 [주환] Routing 방법 수정
  package-lock.json
  package.json
  src/App.tsx
  src/Routes.tsx
  src/components/PressMotion.tsx
  src/components/Transitions.tsx
  src/hooks/useTransitionSelect.ts
  src/layout/PageTransitionLayout.tsx
  src/main.tsx
  src/pages/main/Main.tsx
  src/styles/GlobalStyles.tsx
Labels: page, component

#128 [혜미] main.tsx 주석 추가&수정
  src/components/CoinRotate.tsx
  src/components/Main/CashbackSection.tsx
  src/components/Main/CashbackServiceSection.tsx
  src/components/Main/Filter.tsx
  src/components/Main/FlipCoin.tsx
  src/components/Main/FlipStampBoard.tsx
  src/components/Main/PointHistorySection.tsx
  src/components/Main/StampBoardAnimation.tsx
  src/components/Main/StampBoardSection.tsx
  src/components/Main/StampBox.tsx
  src/components/TitleBox.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: refactor

#135 [주환] User.tsx에서 포인트 설정 메소드 수정
  src/App.tsx
  src/pages/main/Main.tsx
  src/store/User.tsx
Labels: fix, component

#130 [혜미] 스탬프판 애니메이션 동작 수정
  src/components/Main/CashbackServiceSection.tsx
  src/components/Main/FlipStampBoard.tsx
  src/components/Main/StampBoardSection.tsx
  src/pages/main/PointHistory.tsx
Labels: component

#131 [형선] 기부 완료 페이지 추가
  src/App.tsx
  src/Routes.tsx
  src/assets/characterbox/donateComplete.json
  src/assets/donatePage/cloud.json
  src/assets/donatePage/heartD.json
  src/components/Donate/CharacterBox.tsx
  src/components/Donate/Guage.tsx
  src/components/Main/CashbackServiceSection.tsx
  src/layout/DonateMainLayout.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateComplete.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMainBefore.tsx
  src/pages/donate/DonateSetFinish.tsx
  src/pages/main/Main.tsx
  src/pages/main/PointHistory.tsx
Labels: fix, page, component

#138 [주환] resetStamp 전역 메소드 추가
  package.json
  src/data/etfData.ts
  src/server/server.ts
  src/store/User.tsx
Labels: component

#141 [주환] DonateGoal에서 username 전역값으로 변경
  src/data/etfData.js
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateGoal.tsx
Labels: fix, component

#142 [혜미] 콘솔 창에 뜨는 에러 해결
  src/components/Main/CashbackServiceSection.tsx
  src/components/Main/FlipStampBoard.tsx
  src/components/Main/StampBox.tsx
Labels: page

#145 [혜미] ExchageSection 생성, Exchange.tsx 페이지 제작중
  src/Routes.tsx
  src/components/Main/FlipCoin.tsx
  src/components/invest/ExchangeSection.tsx
  src/pages/invest/Exchange.tsx
  src/pages/invest/InvestmentHome.tsx
Labels: page, component

#148 [주환] 전역 상태(User.tsx)에 달러 관련 내용 추가
  src/App.tsx
  src/hooks/useTransitionSelect.ts
  src/pages/invest/ETFList.tsx
  src/pages/main/Main.tsx
  src/store/User.tsx
Labels: component

#149 [주환] Routes 주석 수정
  src/Routes.tsx
Labels: fix

#152 [주환] User 타입 별도 파일로 관리
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix, component

#154 [주환] 전역 메소드 setName 삭제
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix, component

#155 [주환] 리드미 작성
  README.md
  src/store/User.tsx
Labels: readme

#156 [혜미] 투자 상세 내역 페이지 (포인트,달러) 제작, 환전 페이지 디자인, 필터 컴포넌트 추가
  src/Routes.tsx
  src/components/invest/ExchangeSection.tsx
  src/components/invest/KRWFilter.tsx
  src/components/invest/USDFilter.tsx
  src/pages/invest/Exchange.tsx
  src/pages/invest/InvestDollarsHistory.tsx
  src/pages/invest/InvestPointsHistory.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
Labels: page, component

#157 [채연] api 삭제
  src/Routes.tsx
  src/pages/invest/ETFBuy.tsx
  src/pages/invest/Exchange.tsx
  src/pages/invest/InvestmentHome.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/investCategory.tsx
Labels: fix, api

#159 [주환] 환전 2배 이벤트 버그 해결
  src/Routes.tsx
  src/pages/invest/Exchange.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix, api

#160 [주환] 화면 전환 트랜잭션
  src/App.tsx
  src/components/Transitions.tsx
  src/hooks/useTransitionSelect.ts
  src/styles/GlobalStyles.tsx
Labels: fix, component

#161 [주환] Transition 관련 파일 삭제
  src/App.tsx
  src/components/Transitions.tsx
  src/hooks/useTransitionSelect.ts
Labels: fix

#163 [혜미] 출금, 출금 완료 페이지 제작, 경로 주석 처리
  src/Routes.tsx
  src/assets/Main/Withdraw.json
  src/components/Main/Filter.tsx
  src/pages/invest/InvestDollarsHistory.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
  src/pages/main/PointHistory.tsx
  src/pages/main/WithDraw.tsx
  src/pages/main/WithDrawFinish.tsx
  src/store/User.tsx
Labels: page

#164 [형선] 결제 페이지 추가
  src/Routes.tsx
  src/assets/Pay/Logo.png
  src/assets/Pay/payComplete.json
  src/assets/Pay/search.png
  src/assets/Pay/shopping.png
  src/assets/Pay/welcome1.json
  src/assets/Pay/welcome2.json
  src/assets/characterbox/paper.json
  src/assets/donatePage/clap.json
  src/components/Donate/CharacterBox.tsx
  src/components/Pay/PayButtonBox.tsx
  src/components/invest/CategoryBox.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateComplete.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateSetFinish.tsx
  src/pages/pay/Pay.tsx
  src/pages/pay/PayComplete.tsx
  src/pages/pay/PayMain.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix, page

#165 [주환] 페이지 별 뒤로가기 위치 수정
  src/Routes.tsx
  src/layout/DefaultLayout.tsx
  src/layout/DonateMainLayout.tsx
  src/layout/HomeLayout.tsx
  src/store/User.tsx
Labels: fix, page

#166 [주환] 메인 페이지 number animation 추가
  src/components/Donate/CharacterBox.tsx
  src/components/Main/PointHistorySection.tsx
  src/pages/donate/DonateHome.tsx
Labels: component

#167 [주환] 기부 페이지 게이지 애니메이션 추가
  src/components/Donate/CharacterBox.tsx
  src/components/Donate/Guage.tsx
  src/layout/DonateMainLayout.tsx
Labels: component

#168 [주환] 게이지 차는 속도 수정
  src/components/Donate/Guage.tsx
Labels: fix, component

#170 [혜미] 버튼 css&위치 수정, pointhistory.tsx에서 필터 클릭시 뒤에 보이는 배경 제거, 출금 금액 입력시 최대값 설정
  src/components/Main/Filter.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
  src/pages/main/PointHistory.tsx
  src/pages/main/WithDraw.tsx
Labels: page

#171 [형선] 애니메이션 추가
  src/assets/Pay/bus.json
  src/assets/Pay/cafe.json
  src/assets/Pay/fastfood.json
  src/assets/Pay/movie.json
  src/assets/Pay/store.json
  src/assets/Pay/taxi.json
  src/assets/Pay/welcome2.json
  src/components/Donate/CharacterBox.tsx
  src/components/invest/CategoryBox.tsx
  src/pages/donate/DonateComplete.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateSetFinish.tsx
  src/pages/pay/Pay.tsx
  src/pages/pay/PayMain.tsx
Labels: fix

#174 [주환] per 값 없을때 퍼센트 값 처리
  src/components/Donate/Guage.tsx
  src/pages/donate/DonateHome.tsx
Labels: fix

#176 [혜미] css 수정
  src/pages/main/PointHistory.tsx
  src/pages/main/WithDraw.tsx
  src/pages/main/WithDrawFinish.tsx
Labels: page

#177 [주환] 레이아웃 헤더부분 padding 넣음
  src/Routes.tsx
  src/layout/DefaultLayout.tsx
  src/layout/PlusLayout.tsx
Labels: fix

#178 [주환] 캐러셀 수정
  src/components/Main/AdBanner.tsx
Labels: fix

#180 [혜미] 출금시 구분점 추가
  src/pages/donate/Donate.tsx
  src/pages/main/WithDraw.tsx
Labels: page

#182 [혜미] css 수정
  src/pages/invest/InvestmentHome.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
Labels: page

#184 [혜미] css 수정
  src/pages/invest/InvestmentHome.tsx
  src/pages/main/WithDraw.tsx
  src/pages/main/WithDrawFinish.tsx
Labels: page

#185 [형선] 최종 수정2
  src/components/Donate/CharacterBox.tsx
  src/store/User.tsx
Labels: fix

#187 [혜미] pay.tsx에서 username 수정
  src/pages/pay/PayMain.tsx
  src/store/User.tsx
Labels: page

#189 [혜미] 스탬프판 초기화 호출 user 수정
  src/components/Main/StampBoardSection.tsx
Labels: fix

#191 [형선] 핫픽스
  src/pages/donate/DonateGoal.tsx
Labels: fix

#194 [혜미] HOTFIX: 배포 에러 수정
  src/components/Main/AdBanner.tsx
  src/components/Main/Filter.tsx
  src/components/Main/PointHistorySection.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/invest/ETFBuy.tsx
  src/pages/invest/ETFDetail.tsx
  src/pages/invest/ETFSell.tsx
  src/pages/main/WithDrawFinish.tsx
Labels: fix

#195 [형선] HotFix
  src/components/invest/CategoryBox.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateSetFinish.tsx
  src/pages/pay/PayMain.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix

#198 [혜미] HOTFIX 경로 이동 수정
  src/layout/DonateMainLayout.tsx
  src/pages/main/Main.tsx
  src/store/User.tsx
Labels: fix

#201 [주환] vercel.json 설정하여 https 요청 처리
  vercel.json
Labels: fix

#203 [형선] HOTFIX
  src/components/Btn.tsx
  src/components/Donate/CharacterBox.tsx
  src/components/PressMotion.tsx
  src/layout/DefaultLayout.tsx
  src/layout/DonateMainLayout.tsx
  src/layout/ETFListLayout.tsx
  src/layout/HomeLayout.tsx
  src/layout/PlusLayout.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateComplete.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/donate/DonateHome.tsx
  src/pages/donate/DonateMainBefore.tsx
  src/pages/donate/DonateSetFinish.tsx
  src/pages/invest/ETFDetail.tsx
  src/pages/invest/InvestMainBefore.tsx
  src/pages/invest/InvestPointsHistory.tsx
  src/pages/invest/InvestmentHome.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
  src/pages/invest/investCategory.tsx
  src/pages/main/PointHistory.tsx
  src/pages/pay/PayMain.tsx
Labels: fix

#206 [주환] 로그인, 회원가입 구현
  src/Routes.tsx
  src/layout/LoginLayout.tsx
  src/pages/invest/ETFDetail.tsx
  src/pages/login/Login.tsx
  src/pages/login/Signup.tsx
  src/pages/main/Main.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: page

#207 [주환] number animation 수정
  package-lock.json
  package.json
  src/components/Counter.tsx
  src/components/Donate/CharacterBox.tsx
  src/components/Main/PointHistorySection.tsx
Labels: fix, component

#211 [주환] 메인 페이지에 로그아웃 추가
  src/components/Main/PointHistorySection.tsx
  src/layout/DefaultLayout.tsx
  src/pages/invest/InvestmentHome.tsx
Labels: page

#212 [형선] Hotfix
  src/Routes.tsx
  src/components/Btn.tsx
  src/layout/DefaultLayout.tsx
  src/layout/DonateMainLayout.tsx
  src/layout/ETFListLayout.tsx
  src/layout/HeartLayout.tsx
  src/layout/HomeLayout.tsx
  src/layout/LoginLayout.tsx
  src/layout/PlusLayout.tsx
  src/pages/Sign/SignIn.tsx
  src/pages/Sign/SignUp.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateCategory.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/invest/InvestDollarsHistory.tsx
  src/pages/invest/InvestPointsHistory.tsx
  src/pages/invest/KRWExchangeRate.tsx
  src/pages/invest/USDExchangeRate.tsx
  src/pages/main/PointHistory.tsx
  src/pages/main/WithDraw.tsx
  src/pages/pay/PayMain.tsx
Labels: fix

#213 [주환] 레이아웃 헤더 수정
  src/layout/DefaultLayout.tsx
  src/layout/DonateMainLayout.tsx
  src/layout/ETFListLayout.tsx
  src/layout/HeartLayout.tsx
  src/layout/HomeLayout.tsx
  src/layout/LoginLayout.tsx
  src/layout/PlusLayout.tsx
Labels: component

#214 [형선] hotfix
  src/Routes.tsx
  src/layout/DefaultLayout.tsx
  src/pages/Sign/SignIn.tsx
  src/pages/Sign/SignUp.tsx
  src/pages/invest/ETFBuy.tsx
  src/pages/invest/ETFSell.tsx
  src/pages/login/Login.tsx
  src/pages/login/Signup.tsx
Labels: fix

#216 [형선] Hotfix:레이아웃 수정
  src/layout/DefaultLayout.tsx
  src/pages/main/Main.tsx
  src/pages/pay/PayMain.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix

#218 [주환] 자잘한 수정
  src/components/Main/Filter.tsx
  src/pages/main/PointHistory.tsx
  src/pages/pay/PayMain.tsx
Labels: component

#219 [주환] 결제 페이지 CSS 수정
  src/Routes.tsx
  src/pages/pay/PayMain.tsx
Labels: fix

#222 [형선] HotFix: 기부 금액 설정 페이지 수정
  src/layout/DefaultLayout.tsx
  src/pages/donate/Donate.tsx
  src/pages/donate/DonateGoal.tsx
  src/pages/login/Login.tsx
  src/pages/login/Signup.tsx
  src/pages/main/Main.tsx
  src/pages/pay/PayMain.tsx
  src/store/User.tsx
  src/store/UserType.ts
Labels: fix

#223 [주환] 판매 버튼 동작 에러 수정
  src/pages/invest/ETFBuy.tsx
  src/pages/invest/ETFSell.tsx
Labels: fix, component
